Downgrade CodeCov action
CI is failing because of:

```
Error: Codecov: Error importing pgp key
```

Apparently, there is an error in v4, which was caused by
upgrading from v3.

See also the upstream bug reports:

- https://github.com/codecov/codecov-action/issues/1288
- https://github.com/codecov/codecov-action/issues/1279